language: ruby
rvm:
  - 2.6.1
gemfile:
  - src/app/Gemfile
sudo: required
before_install:
  - systemctl start mysql
  - cd ./src/app
  - gem install rails
  - gem update --system
  - gem install bundler