language: ruby
rvm:
  - 2.6.1
gemfile:
  - src/app/Gemfile

before_install:
  - cd ./src/app
  - gem install rails
  - gem update --system
  - gem install bundler
  - bundle install

services:
  - mysql

install:
  - mysql -u root -e "GRANT ALL PRIVILEGES ON app_development.* TO 'rails.user'@'localhost' IDENTIFIED BY 'Rails@123'";
  - mysql -u root -e "GRANT ALL PRIVILEGES ON nome_da_aplicacao_test.* TO 'rails.user'@'localhost' IDENTIFIED BY 'Rails@123'";