language: ruby
rvm:
  - 2.6.1
gemfile:
  - src/app/Gemfile

before_install:
  - cd ./src/app
  - gem install rails
  - gem update --system
  - gem install bundler
  - bundle install
  - psql -c 'create database app_development;' -U postgres
  - psql -c 'create database app_test;' -U postgres
  - psql -c 'CREATE USER railsuser SUPERUSER INHERIT CREATEDB CREATEROLE' -U postgres
  - psql -c "alter user railsuser with password 'Rails@123'" -U postgres
  - apt-get install imagemagick

services:
  - postgresql