language: ruby
rvm:
  - 2.6.1
gemfile:
  - src/app/Gemfile

env:
  global:
    CC_TEST_REPORTER_ID=3310f767d6611bd1260e96aa6b5b6625cdcf72c4d942a8541903d77b96733bc6

before_install:
  - cd ./src/app
  - gem install rails
  - gem update --system
  - gem install bundler
  - bundle install
  - psql -c 'create database app_development;' -U postgres
  - psql -c 'create database app_test;' -U postgres
  - psql -c 'CREATE USER railsuser SUPERUSER INHERIT CREATEDB CREATEROLE' -U postgres
  - psql -c "alter user railsuser with password 'Rails@123'" -U postgres
  - sudo apt-get install imagemagick

before_script:
  - curl -L https://codeclimate.com/downloads/test-reporter/test-reporter-latest-linux-amd64 > ./cc-test-reporter
  - chmod +x ./cc-test-reporter
  - ./cc-test-reporter before-build

script:
  - rails db:migrate
  - rake

services:
  - postgresql

after_script:
  - ./cc-test-reporter after-build --exit-code $TRAVIS_TEST_RESULT